######################## default configuration ####################
baseURL = "https://easyfaas.de/"
title = "EasyFAAS - Easy to use, fast and secure FaaS"
theme = "saasis"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "datafortress.cloud" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here

############################# Imaging ##############################
[imaging]
quality = 100

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"