#################### default parameters ################################
favicon = "images/favicon.png"
logo_text = "easyservices logo"
logo = "images/logo_EasyServices.png"
logo_width = "101px"
# Meta data
description = "Easy and simple Function as a service"
author = "DataFortress.cloud"
# contact info
address = "Georgenstraße 13, 86152 Augsburg, Germany"
mobile = "+49 160 1136770"
email = "easyfaas@datafortress.cloud"
footer_info = "EasyServices is a product of DataFortress.cloud UG"
# form action
contact_form_action = "#" # contact form works with https://formspree.io or formspree alternative
newsletter_form_action = "#" # contact form works with https://formspree.io or formspree alternative
# custom script on header
custom_script= ""

# page header background
page_header= "images/page-header.webp"

# Preloader
[preloader]
enable = false

# Navigation button
[navigation_button]
enable = true
label = "Free Demo"
link = "contact/"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"