baseURL = 'https://easycloudhost.de'
languageCode = 'en-us'
title = 'EasyCloudHost provides several ways for easy Hosting, including Kubernetes, Storage Solutions, Autoscaling and more, all located in Germany for a maximum of compliance and security'
